version: '3'
services:

  web:
    volumes:
      - ./angular:/var/www/html/portfolio
    build: ./angular
    ports:
      - 4200:4200
    hostname: "portfolio.loc"

  api:
    volumes:
      - ./python:/var/www/html/api
    build: ./python
    ports:
      - 5000:5000
    links:
      - database:mysql

  # database container - actency images
  database:
    # @see https://github.com/Actency/docker-mysql
    image: mariadb:latest
    volumes:
      - /python:/var/www/html/api
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=mysqlusr
      - MYSQL_PASSWORD=mysqlpwd
